// ACTIONS_TYPE
export const DATA_LIST_REQUEST = "DATA_LIST_REQUEST";
export const DATA_LIST_SUCCESS = "DATA_LIST_SUCCESS";
export const DATA_LIST_FAIL = "DATA_LIST_FAIL";

export const FILTERED_LIST_SUCCESS = "FILTERED_LIST_SUCCESS";
export const FILTERED_LIST_FAIL = "FILTERED_LIST_FAIL";
